services:
  db-init:
    build: .
    command:
      - /nba_go
      - import-data
    restart: 'no'
    networks:
      - coolify_shared
  api1:
    build: .
    restart: always
    networks:
      - api_network
      - coolify_shared
  api2:
    build: .
    restart: always
    networks:
      - api_network
      - coolify_shared
  api3:
    build: .
    restart: always
    networks:
      - api_network
      - coolify_shared
  nginx:
    image: 'nginx:stable'
    volumes:
      - '/data/nba-go-config/nginx:/etc/nginx:ro'
    depends_on:
      - api1
      - api2
      - api3
    ports:
      - '8081:8080'
    networks:
      - api_network
      - coolify_shared
  prometheus:
    image: 'prom/prometheus:latest'
    volumes:
      - '/data/nba-go-config/prometheus:/etc/prometheus'
      - 'prometheus_data:/prometheus'
    command:
      - '--config.file=/etc/prometheus/prometheus.yml'
    ports:
      - '9091:9090'
    restart: unless-stopped
    networks:
      - api_network
      - coolify_shared
  grafana:
    image: 'grafana/grafana:latest'
    ports:
      - '3001:3000'
    environment:
      - GF_SECURITY_ADMIN_PASSWORD=testing
    volumes:
      - '/data/nba-go-config/grafana/provisioning:/etc/grafana/provisioning'
      - './grafana/dashboards:/var/lib/grafana/dashboards'
      - 'grafana_data:/var/lib/grafana'
    restart: unless-stopped
    networks:
      - api_network
      - coolify_shared
volumes:
  prometheus_data: null
  grafana_data: null
networks:
  api_network:
    driver: bridge
  coolify_shared:
    name: coolify
    external: true
