global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'nba-api'
    static_configs:
      - targets: ['api1:5000', 'api2:5000', 'api3:5000']
    metrics_path: '/metrics'