apiVersion: 1

datasources:
  - name: Prometheus
    uid: PBFA97CFB590B2093
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    jsonData:
      httpMethod: POST

  - name: PostgreSQL-Read-HA
    uid: afxrpob6lpnggc
    type: grafana-postgresql-datasource
    access: proxy
    url: 178.105.149.129:5438
    user: postgres
    database: appdb
    jsonData:
      database: appdb
      sslmode: disable
      maxOpenConns: 50
      maxIdleConns: 20
    secureJsonData:
      password: postgrespassword

  - name: PostgreSQL-Write-HA
    uid: efxrponpevy0wc
    type: grafana-postgresql-datasource
    access: proxy
    url: 178.105.149.129:5437
    user: postgres
    database: appdb
    jsonData:
      database: appdb
      sslmode: disable
      maxOpenConns: 50
      maxIdleConns: 20
    secureJsonData:
      password: postgrespassword